"""Turkish and English forms of the words that make up the narrators' names (YZ-free, hand-written).

Turkish follows the spelling of the TDV İslâm Ansiklopedisi (DİA) closely; English is the plain academic
form used in this project's README (no dots under letters). Keys are written as the words appear; they are
matched after isnady's normalization. Two-word compounds come first ("عبد الله" → Abdullah).
Measured (2026-10-04): the 420 most frequent name words cover about 95% of the words in the names as they
occur in the chains. A name is shown in Latin letters only when its words are known (core.names).
"""

COMPOUNDS = {
    "عبد الله": ("Abdullah", "Abdullah"), "عبد الرحمن": ("Abdurrahman", "Abd al-Rahman"),
    "عبد الملك": ("Abdülmelik", "Abd al-Malik"), "عبد العزيز": ("Abdülazîz", "Abd al-Aziz"),
    "عبد الوارث": ("Abdülvâris", "Abd al-Warith"), "عبد الوهاب": ("Abdülvehhâb", "Abd al-Wahhab"),
    "عبد الرزاق": ("Abdürrezzâk", "Abd al-Razzaq"), "عبد الواحد": ("Abdülvâhid", "Abd al-Wahid"),
    "عبد الأعلى": ("Abdüla'lâ", "Abd al-A'la"), "عبد الحميد": ("Abdülhamîd", "Abd al-Hamid"),
    "عبد الصمد": ("Abdüssamed", "Abd al-Samad"), "عبد المجيد": ("Abdülmecîd", "Abd al-Majid"),
    "عبد الرحيم": ("Abdürrahîm", "Abd al-Rahim"), "عبد الكريم": ("Abdülkerîm", "Abd al-Karim"),
    "عبد الجبار": ("Abdülcebbâr", "Abd al-Jabbar"), "عبد السلام": ("Abdüsselâm", "Abd al-Salam"),
    "عبد المطلب": ("Abdülmuttalib", "Abd al-Muttalib"), "عبد القدوس": ("Abdülkuddûs", "Abd al-Quddus"),
    "عبد الغفار": ("Abdülgaffâr", "Abd al-Ghaffar"), "عبد الحكم": ("Abdülhakem", "Abd al-Hakam"),
    "عبد ربه": ("Abdürabbih", "Abd Rabbih"), "عبد شمس": ("Abdüşems", "Abd Shams"),
    "عبيد الله": ("Ubeydullah", "Ubayd Allah"), "أبو بكر": ("Ebû Bekr", "Abu Bakr"), "أبي بكر": ("Ebû Bekr", "Abi Bakr"),
    "أبو هريرة": ("Ebû Hüreyre", "Abu Hurayra"), "أبي هريرة": ("Ebû Hüreyre", "Abi Hurayra"),
    "أبو داود": ("Ebû Dâvûd", "Abu Dawud"), "أبي داود": ("Ebû Dâvûd", "Abi Dawud"),
    "أبو ذر": ("Ebû Zer", "Abu Dharr"), "أبي ذر": ("Ebû Zer", "Abi Dharr"),
    "أبي وقاص": ("Ebû Vakkâs", "Abi Waqqas"), "أبي طالب": ("Ebû Tâlib", "Abi Talib"),
    "أبي سفيان": ("Ebû Süfyân", "Abi Sufyan"), "أبو سفيان": ("Ebû Süfyân", "Abu Sufyan"),
    "أم سلمة": ("Ümmü Seleme", "Umm Salama"), "أم حبيبة": ("Ümmü Habîbe", "Umm Habiba"),
    "أبي شيبة": ("Ebû Şeybe", "Abi Shayba"), "أبي أويس": ("Ebû Üveys", "Abi Uways"),
}

WORDS = {
    # particles
    "بن": ("b.", "b."), "بنت": ("bint", "bint"), "أبو": ("Ebû", "Abu"), "أبي": ("Ebû", "Abi"), "أبا": ("Ebâ", "Aba"),
    "أم": ("Ümmü", "Umm"),
    # first names, fathers, kunyas
    "عبد": ("Abd", "Abd"), "الله": ("Allah", "Allah"), "محمد": ("Muhammed", "Muhammad"), "سعيد": ("Saîd", "Sa'id"),
    "عمرو": ("Amr", "Amr"), "عمر": ("Ömer", "Umar"), "سليمان": ("Süleyman", "Sulayman"), "إبراهيم": ("İbrâhim", "Ibrahim"),
    "عبيد": ("Ubeyd", "Ubayd"), "يحيى": ("Yahyâ", "Yahya"), "يزيد": ("Yezîd", "Yazid"), "بكر": ("Bekr", "Bakr"),
    "عثمان": ("Osman", "Uthman"), "موسى": ("Mûsâ", "Musa"), "إسماعيل": ("İsmâil", "Isma'il"), "هريرة": ("Hüreyre", "Hurayra"),
    "خالد": ("Hâlid", "Khalid"), "مالك": ("Mâlik", "Malik"), "علي": ("Ali", "Ali"), "الحجاج": ("el-Haccâc", "al-Hajjaj"),
    "سعد": ("Sa'd", "Sa'd"), "مسلم": ("Müslim", "Muslim"), "شعبة": ("Şu'be", "Shu'ba"), "زيد": ("Zeyd", "Zayd"),
    "الخطاب": ("el-Hattâb", "al-Khattab"), "الحارث": ("el-Hâris", "al-Harith"), "الورد": ("el-Verd", "al-Ward"),
    "عائشة": ("Âişe", "A'isha"), "مسدد": ("Müsedded", "Musaddad"), "مسرهد": ("Müserhed", "Musarhad"),
    "مسربل": ("Müserbel", "Musarbal"), "عباس": ("Abbâs", "Abbas"), "الزبير": ("ez-Zübeyr", "al-Zubayr"),
    "أحمد": ("Ahmed", "Ahmad"), "سلمة": ("Seleme", "Salama"), "يوسف": ("Yûsuf", "Yusuf"), "العزيز": ("el-Azîz", "al-Aziz"),
    "عروة": ("Urve", "Urwa"), "مهران": ("Mihrân", "Mihran"), "قيس": ("Kays", "Qays"), "الحكم": ("el-Hakem", "al-Hakam"),
    "إسحاق": ("İshak", "Ishaq"), "الملك": ("el-Melik", "al-Malik"), "هشام": ("Hişâm", "Hisham"), "وهب": ("Vehb", "Wahb"),
    "نافع": ("Nâfi'", "Nafi'"), "قتيبة": ("Kuteybe", "Qutayba"), "جميل": ("Cemîl", "Jamil"), "صالح": ("Sâlih", "Salih"),
    "جعفر": ("Ca'fer", "Ja'far"), "الحسن": ("el-Hasan", "al-Hasan"), "حفص": ("Hafs", "Hafs"), "عامر": ("Âmir", "Amir"),
    "جابر": ("Câbir", "Jabir"), "الفضل": ("el-Fazl", "al-Fadl"), "دكين": ("Dükeyn", "Dukayn"), "عقيل": ("Ukayl", "Uqayl"),
    "كثير": ("Kesîr", "Kathir"), "اليمان": ("el-Yemân", "al-Yaman"), "حماد": ("Hammâd", "Hammad"), "العوام": ("el-Avvâm", "al-Awwam"),
    "زياد": ("Ziyâd", "Ziyad"), "عيسى": ("Îsâ", "Isa"), "القاسم": ("el-Kâsım", "al-Qasim"), "قتادة": ("Katâde", "Qatada"),
    "معاوية": ("Muâviye", "Mu'awiya"), "المغيرة": ("el-Mugîre", "al-Mughira"), "عقبة": ("Ukbe", "Uqba"),
    "مسلمة": ("Mesleme", "Maslama"), "دينار": ("Dînâr", "Dinar"), "عمران": ("İmrân", "Imran"), "الوليد": ("el-Velîd", "al-Walid"),
    "حرب": ("Harb", "Harb"), "سنان": ("Sinân", "Sinan"), "قعنب": ("Ka'neb", "Qa'nab"), "سهل": ("Sehl", "Sahl"),
    "بشر": ("Bişr", "Bishr"), "كيسان": ("Keysân", "Kaysan"), "عطاء": ("Atâ", "Ata'"), "سفيان": ("Süfyân", "Sufyan"),
    "بشير": ("Beşîr", "Bashir"), "عاصم": ("Âsım", "Asim"), "معاذ": ("Muâz", "Mu'adh"), "حبيب": ("Habîb", "Habib"),
    "إياس": ("İyâs", "Iyas"), "داود": ("Dâvûd", "Dawud"), "ثابت": ("Sâbit", "Thabit"), "بكير": ("Bükeyr", "Bukayr"),
    "آدم": ("Âdem", "Adam"), "حميد": ("Humeyd", "Humayd"), "العلاء": ("el-Alâ", "al-Ala'"), "يسار": ("Yesâr", "Yasar"),
    "أنس": ("Enes", "Anas"), "سالم": ("Sâlim", "Salim"), "بشار": ("Beşşâr", "Bashshar"), "نصر": ("Nasr", "Nasr"),
    "هرمز": ("Hürmüz", "Hurmuz"), "كعب": ("Ka'b", "Ka'b"), "وائل": ("Vâil", "Wa'il"), "ذكوان": ("Zekvân", "Dhakwan"),
    "هارون": ("Hârûn", "Harun"), "المسيب": ("el-Müseyyeb", "al-Musayyab"), "عدي": ("Adî", "Adi"), "هلال": ("Hilâl", "Hilal"),
    "المثنى": ("el-Müsennâ", "al-Muthanna"), "حزن": ("Hazn", "Hazn"), "شقيق": ("Şakîk", "Shaqiq"), "سليم": ("Süleym", "Sulaym"),
    "حنبل": ("Hanbel", "Hanbal"), "الوارث": ("el-Vâris", "al-Warith"), "يونس": ("Yûnus", "Yunus"), "ربيعة": ("Rebîa", "Rabi'a"),
    "رافع": ("Râfi'", "Rafi'"), "عياش": ("Ayyâş", "Ayyash"), "عباد": ("Abbâd", "Abbad"), "درهم": ("Dirhem", "Dirham"),
    "عجلان": ("Aclân", "Ajlan"), "يعقوب": ("Ya'kûb", "Ya'qub"), "المنذر": ("el-Münzir", "al-Mundhir"), "الربيع": ("er-Rebî'", "al-Rabi'"),
    "حمزة": ("Hamza", "Hamza"), "جبير": ("Cübeyr", "Jubayr"), "أيوب": ("Eyyûb", "Ayyub"), "الحسين": ("el-Hüseyin", "al-Husayn"),
    "ميمون": ("Meymûn", "Maymun"), "عون": ("Avn", "Awn"), "جرير": ("Cerîr", "Jarir"), "عمير": ("Umeyr", "Umayr"),
    "حازم": ("Hâzim", "Hazim"), "كريب": ("Kureyb", "Kurayb"), "أسامة": ("Üsâme", "Usama"), "البراء": ("el-Berâ", "al-Bara'"),
    "حصين": ("Husayn", "Husayn"), "العاص": ("el-Âs", "al-As"), "طلحة": ("Talha", "Talha"), "ميسرة": ("Meysere", "Maysara"),
    "حسان": ("Hassân", "Hassan"), "عازب": ("Âzib", "Azib"), "الأسود": ("el-Esved", "al-Aswad"), "أمية": ("Ümeyye", "Umayya"),
    "مسعود": ("Mes'ûd", "Mas'ud"), "حكيم": ("Hakîm", "Hakim"), "مروان": ("Mervân", "Marwan"), "جبلة": ("Cebele", "Jabala"),
    "منصور": ("Mansûr", "Mansur"), "سويد": ("Süveyd", "Suwayd"), "أوس": ("Evs", "Aws"), "مسروق": ("Mesrûk", "Masruq"),
    "الوهاب": ("el-Vehhâb", "al-Wahhab"), "علقمة": ("Alkame", "Alqama"), "عمارة": ("Umâre", "Umara"), "فضيل": ("Fudayl", "Fudayl"),
    "النعمان": ("en-Nu'mân", "al-Nu'man"), "صفوان": ("Safvân", "Safwan"), "راشد": ("Râşid", "Rashid"), "شراحيل": ("Şerâhîl", "Sharahil"),
    "سلام": ("Sellâm", "Sallam"), "الجراح": ("el-Cerrâh", "al-Jarrah"), "عوانة": ("Avâne", "Awana"), "غياث": ("Gıyâs", "Ghiyath"),
    "طاوس": ("Tâvûs", "Tawus"), "وضاح": ("Vaddâh", "Waddah"), "مخلد": ("Mahled", "Makhlad"), "دعامة": ("Diâme", "Di'ama"),
    "أسلم": ("Eslem", "Aslam"), "مصعب": ("Mus'ab", "Mus'ab"), "وهيب": ("Vüheyb", "Wuhayb"), "الضحاك": ("ed-Dahhâk", "al-Dahhak"),
    "الأجدع": ("el-Ecda'", "al-Ajda'"), "عمار": ("Ammâr", "Ammar"), "مرة": ("Mürre", "Murra"), "السائب": ("es-Sâib", "al-Sa'ib"),
    "حاتم": ("Hâtim", "Hatim"), "شداد": ("Şeddâd", "Shaddad"), "بلال": ("Bilâl", "Bilal"), "الهيثم": ("el-Heysem", "al-Haytham"),
    "ثعلبة": ("Sa'lebe", "Tha'laba"), "المبارك": ("el-Mübârek", "al-Mubarak"), "زريع": ("Zürey'", "Zuray'"), "عبيدة": ("Ubeyde", "Ubayda"),
    "شريح": ("Şüreyh", "Shurayh"), "رباح": ("Rebâh", "Rabah"), "وكيع": ("Vekî'", "Waki'"), "جبر": ("Cebr", "Jabr"),
    "سيرين": ("Sîrîn", "Sirin"), "واقد": ("Vâkıd", "Waqid"), "مليح": ("Melîh", "Malih"), "هاشم": ("Hâşim", "Hashim"),
    "وقاص": ("Vakkâs", "Waqqas"), "عتبة": ("Utbe", "Utba"), "الحميد": ("el-Hamîd", "al-Hamid"), "طالب": ("Tâlib", "Talib"),
    "مجاهد": ("Mücâhid", "Mujahid"), "عياض": ("İyâz", "Iyad"), "المجيد": ("el-Mecîd", "al-Majid"), "هشيم": ("Hüşeym", "Hushaym"),
    "عيينة": ("Uyeyne", "Uyayna"), "عبادة": ("Ubâde", "Ubada"), "النضر": ("en-Nadr", "al-Nadr"), "زهير": ("Züheyr", "Zuhayr"),
    "شعيب": ("Şuayb", "Shu'ayb"), "المنكدر": ("el-Münkedir", "al-Munkadir"), "شيبان": ("Şeybân", "Shayban"), "يعلى": ("Ya'lâ", "Ya'la"),
    "حيان": ("Hayyân", "Hayyan"), "مقاتل": ("Mukâtil", "Muqatil"), "محمود": ("Mahmûd", "Mahmud"), "معتمر": ("Mu'temir", "Mu'tamir"),
    "مهدي": ("Mehdî", "Mahdi"), "ذر": ("Zer", "Dharr"), "بريدة": ("Büreyde", "Burayda"), "غزوان": ("Gazvân", "Ghazwan"),
    "قدامة": ("Kudâme", "Qudama"), "حارثة": ("Hârise", "Haritha"), "سمرة": ("Semüre", "Samura"), "مطعم": ("Mut'im", "Mut'im"),
    "فروخ": ("Ferrûh", "Farrukh"), "الصلت": ("es-Salt", "al-Salt"), "الصباح": ("es-Sabbâh", "al-Sabbah"), "صدقة": ("Sadaka", "Sadaqa"),
    "شريك": ("Şerîk", "Sharik"), "بحر": ("Bahr", "Bahr"), "بقية": ("Bakıyye", "Baqiyya"), "زاذان": ("Zâzân", "Zadhan"),
    "فضالة": ("Fadâle", "Fadala"), "عوف": ("Avf", "Awf"), "عطية": ("Atıyye", "Atiyya"), "الفرج": ("el-Ferec", "al-Faraj"),
    "هانئ": ("Hâni'", "Hani'"), "المفضل": ("el-Mufaddal", "al-Mufaddal"), "العباس": ("el-Abbâs", "al-Abbas"), "أبان": ("Ebân", "Aban"),
    "نوفل": ("Nevfel", "Nawfal"), "السري": ("es-Serî", "al-Sari"), "أسماء": ("Esmâ", "Asma'"), "ضمرة": ("Damre", "Damra"),
    "نفيع": ("Nüfey'", "Nufay'"), "خلاد": ("Hallâd", "Khallad"), "زكريا": ("Zekeriyyâ", "Zakariyya"), "لاحق": ("Lâhik", "Lahiq"),
    "مرثد": ("Mersed", "Marthad"), "همام": ("Hemmâm", "Hammam"), "خليفة": ("Halîfe", "Khalifa"), "شرحبيل": ("Şürahbîl", "Shurahbil"),
    "نمير": ("Nümeyr", "Numayr"), "الواحد": ("el-Vâhid", "al-Wahid"), "حبان": ("Habbân", "Habban"), "جنادة": ("Cünâde", "Junada"),
    "عمرة": ("Amra", "Amra"), "فليح": ("Füleyh", "Fulayh"), "الأعلى": ("el-A'lâ", "al-A'la"), "زائدة": ("Zâide", "Za'ida"),
    "حذيفة": ("Huzeyfe", "Hudhayfa"), "بريد": ("Büreyd", "Burayd"), "مريم": ("Meryem", "Maryam"), "سهيل": ("Süheyl", "Suhayl"),
    "روح": ("Ravh", "Rawh"), "معبد": ("Ma'bed", "Ma'bad"), "الليث": ("el-Leys", "al-Layth"), "باذام": ("Bâzâm", "Badham"),
    "حجاج": ("Haccâc", "Hajjaj"), "صهيب": ("Suheyb", "Suhayb"), "الخصيب": ("el-Hasîb", "al-Khasib"), "مقسم": ("Miksem", "Miqsam"),
    "حسين": ("Hüseyin", "Husayn"), "طارق": ("Târık", "Tariq"), "الجعد": ("el-Ca'd", "al-Ja'd"), "سلمان": ("Selmân", "Salman"),
    "جندب": ("Cündeb", "Jundab"), "ليلى": ("Leylâ", "Layla"), "أرطبان": ("Artabân", "Artaban"), "هناد": ("Hennâd", "Hannad"),
    "أسيد": ("Üseyd", "Usayd"), "بسر": ("Büsr", "Busr"), "غسان": ("Gassân", "Ghassan"), "الرحيم": ("er-Rahîm", "al-Rahim"),
    "الصمد": ("es-Samed", "al-Samad"), "شيبة": ("Şeybe", "Shayba"), "صبيح": ("Subeyh", "Subayh"), "شهاب": ("Şihâb", "Shihab"),
    "خبيب": ("Hubeyb", "Khubayb"), "كلدة": ("Kelede", "Kalada"), "قرة": ("Kurre", "Qurra"), "فاطمة": ("Fâtıma", "Fatima"),
    "سلم": ("Selm", "Salm"), "حفصة": ("Hafsa", "Hafsa"), "طلق": ("Talk", "Talq"), "مخرمة": ("Mahreme", "Makhrama"),
    "نفيل": ("Nüfeyl", "Nufayl"), "نعيم": ("Nuaym", "Nu'aym"), "الرحمن": ("er-Rahmân", "al-Rahman"), "الصديق": ("es-Sıddîk", "al-Siddiq"),
    "سيف": ("Seyf", "Sayf"), "زرارة": ("Zürâre", "Zurara"), "الأشعث": ("el-Eş'as", "al-Ash'ath"),
    "مستورد": ("Müstevrid", "Mustawrid"), "طريف": ("Tarîf", "Tarif"), "شداد": ("Şeddâd", "Shaddad"),
    "الحجاج": ("el-Haccâc", "al-Hajjaj"), "شعيب": ("Şuayb", "Shu'ayb"), "سورة": ("Sevre", "Sawra"),
    # nisbas (with the article)
    "البصري": ("el-Basrî", "al-Basri"), "الدوسي": ("ed-Devsî", "al-Dawsi"), "الكوفي": ("el-Kûfî", "al-Kufi"),
    "الأسدي": ("el-Esedî", "al-Asadi"), "العتكي": ("el-Atekî", "al-Ataki"), "الأنصاري": ("el-Ensârî", "al-Ansari"),
    "الأزدي": ("el-Ezdî", "al-Azdi"), "المدني": ("el-Medenî", "al-Madani"), "الكاهلي": ("el-Kâhilî", "al-Kahili"),
    "التميمي": ("et-Temîmî", "al-Tamimi"), "العبدي": ("el-Abdî", "al-Abdi"), "المنقري": ("el-Minkarî", "al-Minqari"),
    "الهمداني": ("el-Hemdânî", "al-Hamdani"), "التنيسي": ("et-Tinnîsî", "al-Tinnisi"), "المكي": ("el-Mekkî", "al-Makki"),
    "المصري": ("el-Mısrî", "al-Misri"), "التيمي": ("et-Teymî", "al-Taymi"), "السلمي": ("es-Sülemî", "al-Sulami"),
    "القرشي": ("el-Kureşî", "al-Qurashi"), "العدوي": ("el-Adevî", "al-Adawi"), "البهراني": ("el-Behrânî", "al-Bahrani"),
    "الواسطي": ("el-Vâsıtî", "al-Wasiti"), "الباهلي": ("el-Bâhilî", "al-Bahili"), "الحضرمي": ("el-Hadramî", "al-Hadrami"),
    "المروزي": ("el-Mervezî", "al-Marwazi"), "الأعرج": ("el-A'rac", "al-A'raj"), "السدوسي": ("es-Sedûsî", "al-Sadusi"),
    "الليثي": ("el-Leysî", "al-Laythi"), "اليشكري": ("el-Yeşkürî", "al-Yashkuri"), "الأسلمي": ("el-Eslemî", "al-Aslami"),
    "المخزومي": ("el-Mahzûmî", "al-Makhzumi"), "الأيلي": ("el-Eylî", "al-Ayli"), "الواشحي": ("el-Vâşihî", "al-Washihi"),
    "العنزي": ("el-Anezî", "al-Anazi"), "الهلالي": ("el-Hilâlî", "al-Hilali"), "الثقفي": ("es-Sekafî", "al-Thaqafi"),
    "الجهني": ("el-Cühenî", "al-Juhani"), "الضبي": ("ed-Dabbî", "al-Dabbi"), "الفراهيدي": ("el-Ferâhîdî", "al-Farahidi"),
    "البزاز": ("el-Bezzâz", "al-Bazzaz"), "الشامي": ("eş-Şâmî", "al-Shami"), "الطائي": ("et-Tâî", "al-Ta'i"),
    "الخزاعي": ("el-Huzâî", "al-Khuza'i"), "الكندي": ("el-Kindî", "al-Kindi"), "الهاشمي": ("el-Hâşimî", "al-Hashimi"),
    "الحنفي": ("el-Hanefî", "al-Hanafi"), "الغفاري": ("el-Gıfârî", "al-Ghifari"), "البغدادي": ("el-Bağdâdî", "al-Baghdadi"),
    "البجلي": ("el-Becelî", "al-Bajali"), "الحمصي": ("el-Hımsî", "al-Himsi"), "الشعبي": ("eş-Şa'bî", "al-Sha'bi"),
    "الصنعاني": ("es-San'ânî", "al-San'ani"), "الضبعي": ("ed-Dubaî", "al-Duba'i"), "الأموي": ("el-Emevî", "al-Umawi"),
    "العامري": ("el-Âmirî", "al-Amiri"), "المقبري": ("el-Makburî", "al-Maqburi"), "الدمشقي": ("ed-Dımaşkî", "al-Dimashqi"),
    "الرؤاسي": ("er-Ruâsî", "al-Ru'asi"), "الجزري": ("el-Cezerî", "al-Jazari"), "النخعي": ("en-Nehaî", "al-Nakha'i"),
    "المزني": ("el-Müzenî", "al-Muzani"), "اليماني": ("el-Yemânî", "al-Yamani"), "الفزاري": ("el-Fezârî", "al-Fazari"),
    "السوائي": ("es-Süvâî", "al-Suwa'i"), "العجلي": ("el-İclî", "al-Ijli"), "المحاربي": ("el-Muhâribî", "al-Muharibi"),
    "الأشجعي": ("el-Eşcaî", "al-Ashja'i"), "السمان": ("es-Semmân", "al-Samman"), "القيسي": ("el-Kaysî", "al-Qaysi"),
    "الكسائي": ("el-Kisâî", "al-Kisa'i"), "الرقاشي": ("er-Rakkâşî", "al-Raqqashi"), "الكلابي": ("el-Kilâbî", "al-Kilabi"),
    "الأحمسي": ("el-Ahmesî", "al-Ahmasi"), "الأنصارية": ("el-Ensâriyye", "al-Ansariyya"), "البناني": ("el-Bünânî", "al-Bunani"),
    "الشيباني": ("eş-Şeybânî", "al-Shaybani"), "الأشعري": ("el-Eş'arî", "al-Ash'ari"), "الغطفاني": ("el-Gatafânî", "al-Ghatafani"),
    "الخراساني": ("el-Horasânî", "al-Khurasani"), "النهدي": ("en-Nehdî", "al-Nahdi"), "الهباري": ("el-Hebbârî", "al-Habbari"),
    "الكناني": ("el-Kinânî", "al-Kinani"), "البلخي": ("el-Belhî", "al-Balkhi"), "السعدي": ("es-Sa'dî", "al-Sa'di"),
    "الهذلي": ("el-Hüzelî", "al-Hudhali"), "الجعفي": ("el-Cu'fî", "al-Ju'fi"), "الطائفي": ("et-Tâifî", "al-Ta'ifi"),
    "المازني": ("el-Mâzinî", "al-Mazini"), "العبسي": ("el-Absî", "al-Absi"), "الرازي": ("er-Râzî", "al-Razi"),
    "الحلبي": ("el-Halebî", "al-Halabi"), "الزهري": ("ez-Zührî", "al-Zuhri"), "الثوري": ("es-Sevrî", "al-Thawri"),
    "البخاري": ("el-Buhârî", "al-Bukhari"), "السجستاني": ("es-Sicistânî", "al-Sijistani"), "العسقلاني": ("el-Askalânî", "al-Asqalani"),
    "الجمحي": ("el-Cumahî", "al-Jumahi"), "الأصبهاني": ("el-İsfahânî", "al-Isfahani"), "النيسابوري": ("en-Nîsâbûrî", "al-Naysaburi"),
    "الحمصي": ("el-Hımsî", "al-Himsi"), "الأوزاعي": ("el-Evzâî", "al-Awza'i"), "الأعمش": ("el-A'meş", "al-A'mash"),
    "المدائني": ("el-Medâinî", "al-Mada'ini"), "الإفريقي": ("el-İfrîkî", "al-Ifriqi"),
    "الخزرجي": ("el-Hazrecî", "al-Khazraji"), "الأوسي": ("el-Evsî", "al-Awsi"), "الترمذي": ("et-Tirmizî", "al-Tirmidhi"),
    "النسائي": ("en-Nesâî", "al-Nasa'i"), "القزويني": ("el-Kazvînî", "al-Qazwini"), "القطان": ("el-Kattân", "al-Qattan"),
}

# words where a Latin name stops (notes, alternatives, "client of", reading notes): the name before them is complete
STOPS = {"ويقال", "يقال", "واسم", "اسمه", "أو", "عن", "قيل", "وقيل", "هو", "من", "ثم", "شيخ", "نزيل", "والد", "أخو", "زوج",
         "آخر", "مولاهم", "مولى", "الميم", "اللام", "الهاء", "الواو", "الكاف", "الدال", "بفتحتين", "بعدها", "آخره", "النبي",
         "كوفي", "بصري", "حجازي", "صاحب", "صحابي", "صحابية", "مشهور", "المشهور"}
